### ISSUE TITLE
windows cmd use 'webmonkey --help' error

### ISSUE THREAD

**Issue by hhhhjjj** [Wildhoney/Webmonkey#30]
Step1.use 'npm install -g' in cmd of D:\webmonkey\Webmonkey
Step2.use 'webmonkey --help' in cmd

ERROR:
fs.js:497
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'D:\D:\webmonkey\Webmonkey\package.json'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at file:///D:/webmonkey/Webmonkey/bin/index.mjs:19:8
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:\\D:\\webmonkey\\Webmonkey\\package.json'
}

Then,in Webmonkey\bin\index.mjs
I add console.log(bin); in line19
result is /D:/webmonkey/Webmonkey/bin

**Comment by hhhhjjj** [comment]
I use absolute path of package.json to resolve this issue
